const CONFIG={weddingAt:'2026-09-20T08:30:00+07:00',rsvpEndpoint:''};
const galleryIds=['1lWKyAkxKc9aIBl_8am5EA6oEMnZC7833','1JJ88r6-3YrbioTjVG-7F5ltFUM5ftwaz','11oAWP4WYIKnN0SasgAwnKLohF5vbxEeQ','14Ej33bqh0q_Aq6xYH7ahs8mTsJQhpBX9','1b6biMgF8qbE3yXRb3FCJdZxcnoubo4CV','1fHn42I1I8ZHF-ipb43GMkVemZaka5nXB','18Lql5KmhlSBVUFh5CYVX4TWIzC0OYqrt','1-1ZkcpQWgrGmAuqq6Kz7fGrkFnLMJcoz','1YFI_EqbpEyFlSb2PY2KB4cer8oUvq7KG','1FOJyyztPvAT4D3jxXrm6ZPapi-AMAkaX','1qrxCkeWRRK36R0lFnLj4OKcgkBQJOVrb','1ZuzBkr-f6-Mvggw8B9nFwayRg5JxLVGl','1gU37VdzL509T2CAZDvqrrAozd-TueL1m'];
const $=s=>document.querySelector(s);const opening=$('#opening'),site=$('#site'),openBtn=$('#openInvitation'),music=$('#bgMusic'),musicBtn=$('#musicButton'),musicIcon=$('#musicIcon');let observer;let musicPlaying=false;let visibleCount=8;let musicObjectUrl='';let musicReady=false;
function setMusicUi(playing){musicPlaying=playing;musicBtn?.classList.toggle('is-playing',playing);musicBtn?.setAttribute('aria-label',playing?'Tắt nhạc':'Bật nhạc');if(musicIcon)musicIcon.textContent=playing?'♫':'♪';}
function initMusicSource(){if(!music||!window.WEDDING_MUSIC_DATA)return false;try{const data=window.WEDDING_MUSIC_DATA;if(typeof data!=='string')return false;if(data.startsWith('data:audio/')){const comma=data.indexOf(',');if(comma<0)return false;const meta=data.slice(0,comma);const payload=data.slice(comma+1);const isBase64=/;base64/i.test(meta);let bytes;if(isBase64){const binary=atob(payload);bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);}else{const decoded=decodeURIComponent(payload);bytes=new TextEncoder().encode(decoded);}const mime=(meta.match(/^data:([^;,]+)/)||[])[1]||'audio/mpeg';const blob=new Blob([bytes],{type:mime});musicObjectUrl=URL.createObjectURL(blob);music.src=musicObjectUrl;}else{music.src=data;}music.preload='auto';music.loop=true;music.load();musicReady=true;return true;}catch(err){console.warn('Music init failed',err);try{music.src=window.WEDDING_MUSIC_DATA;music.load();musicReady=!!music.src;return musicReady;}catch(_){return false;}}}
initMusicSource();
function setupObserver(){const els=document.querySelectorAll('.reveal:not(.is-visible)');if(!('IntersectionObserver'in window)){els.forEach(el=>el.classList.add('is-visible'));return;}if(!observer)observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.08,rootMargin:'0px 0px -4% 0px'});els.forEach(el=>observer.observe(el));}
function showHero(){const stack=$('.photo-stack.hero-reveal'),copy=$('.hero-copy.hero-reveal');setTimeout(()=>stack?.classList.add('is-visible'),160);setTimeout(()=>{copy?.classList.add('is-visible');copy?.classList.add('hero-lines-visible')},520);}
const heroStack=$('.photo-stack');if(heroStack){const cards=[...heroStack.querySelectorAll('.photo-card')];cards.forEach(card=>card.addEventListener('click',e=>{e.preventDefault();const back=card.classList.contains('back');const swapped=heroStack.classList.contains('is-swapped');if((back&&!swapped)||(!back&&swapped))heroStack.classList.toggle('is-swapped');}));}
async function startMusic(){if(!music)return false;if(!musicReady&&!initMusicSource())return false;try{music.muted=false;music.volume=.72;const p=music.play();if(p&&typeof p.then==='function')await p;setMusicUi(!music.paused);return !music.paused;}catch(e){console.warn('Music play blocked',e);setMusicUi(false);return false;}}
function stopMusic(){if(music)music.pause();setMusicUi(false);}
openBtn.addEventListener('click',()=>{opening.classList.add('is-open');site.classList.remove('is-locked');document.body.classList.add('invitation-opened');setupObserver();showHero();startMusic();});
musicBtn.addEventListener('click',()=>{if(!music)return;if(!music.paused)stopMusic();else startMusic();});
music?.addEventListener('play',()=>setMusicUi(true));music?.addEventListener('playing',()=>setMusicUi(true));music?.addEventListener('pause',()=>setMusicUi(false));music?.addEventListener('ended',()=>setMusicUi(false));music?.addEventListener('error',()=>{console.warn('Audio error',music.error);setMusicUi(false);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&music&&!music.paused)setMusicUi(true);});window.addEventListener('pagehide',()=>{if(musicObjectUrl)URL.revokeObjectURL(musicObjectUrl);});
const guest=new URLSearchParams(location.search).get('guest');if(guest){const v=guest.trim().slice(0,80);$('#guestGreeting').textContent=`Thân mời ${v} đến chung vui cùng Thắng & Yến`;$('#guestHidden').value=v}else $('#guestGreeting').textContent='Thân mời bạn đến chung vui cùng Thắng & Yến';
function tick(){const d=Math.max(0,new Date(CONFIG.weddingAt)-new Date());$('#days').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('#hours').textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');$('#minutes').textContent=String(Math.floor(d/60000)%60).padStart(2,'0');$('#seconds').textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}tick();setInterval(tick,1000);
const gallery=$('#gallery'),showMore=$('#showMore'),lightbox=$('#lightbox'),lightboxImage=$('#lightboxImage');const thumb=(id,s=1200)=>`https://drive.google.com/thumbnail?id=${id}&sz=w${s}`;function openLightbox(src){lightboxImage.src=src;lightbox.classList.add('is-open');lightbox.setAttribute('aria-hidden','false')}function renderGallery(){gallery.innerHTML='';[...new Set(galleryIds)].slice(0,visibleCount).forEach((id,i)=>{const wrap=document.createElement('div');wrap.className=`gallery-item reveal ${i%4===0?'from-left':i%4===1?'from-bottom':i%4===2?'zoom':'from-right'} gallery-style-${i%5}`;const img=document.createElement('img');img.loading='lazy';img.alt=`Ảnh cưới Thắng và Yến ${i+1}`;img.src=thumb(id);img.addEventListener('click',()=>openLightbox(thumb(id,1800)));wrap.appendChild(img);gallery.appendChild(wrap)});showMore.style.display=visibleCount>=galleryIds.length?'none':'flex';showMore.textContent=`Xem thêm ảnh (${galleryIds.length-visibleCount})`;setupObserver();}showMore.addEventListener('click',()=>{visibleCount=Math.min(galleryIds.length,visibleCount+5);renderGallery()});renderGallery();setupObserver();
const heartField=$('#heartField');function spawnHeart(){if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const h=document.createElement('span');h.className='floating-heart';h.textContent=Math.random()>.38?'♡':'♥';h.style.left=`${Math.random()*96}%`;h.style.fontSize=`${15+Math.random()*20}px`;h.style.animationDuration=`${7+Math.random()*6}s`;h.style.setProperty('--drift',`${-70+Math.random()*140}px`);heartField.appendChild(h);setTimeout(()=>h.remove(),13500)}setInterval(spawnHeart,1500);for(let i=0;i<4;i++)setTimeout(spawnHeart,i*550);
const form=$('#rsvpForm'),status=$('#formStatus');form.addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(form).entries());payload.createdAt=new Date().toISOString();if(!CONFIG.rsvpEndpoint){localStorage.setItem('thangyen-rsvp-demo',JSON.stringify(payload));status.textContent='Đã lưu xác nhận trên thiết bị.';return}status.textContent='Đang gửi xác nhận...';try{await fetch(CONFIG.rsvpEndpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});status.textContent='Cảm ơn bạn! Thắng & Yến đã nhận được xác nhận ♥';form.reset()}catch(e){status.textContent='Chưa gửi được. Vui lòng thử lại sau.'}});
const giftModal=$('#giftModal');$('#openGift').addEventListener('click',()=>{giftModal.classList.add('is-open');giftModal.setAttribute('aria-hidden','false')});$('#closeGift').addEventListener('click',()=>giftModal.classList.remove('is-open'));giftModal.addEventListener('click',e=>{if(e.target===giftModal)giftModal.classList.remove('is-open')});$('#closeLightbox').addEventListener('click',()=>lightbox.classList.remove('is-open'));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.classList.remove('is-open')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){giftModal.classList.remove('is-open');lightbox.classList.remove('is-open')}});