const CONFIG={weddingAt:'2026-09-20T08:30:00+07:00',rsvpEndpoint:''};
const galleryIds=['1p9GwZmF0ik5puonJBQE-NRqd-uqY3B6g','1r9xWgk2xop17D-sB51hpntKs4ZSIvjw1','17pz8BdkiOuW5ZiwX6KnNx_-Xx1jyhR4e','1dYlB7gtgsSNSnS9P2t6Msl6peYz-HYkY','1y4xjf6jwPKpTQ1Qf7mVm-5uocI-2DtuN','12CwG6BZzJE1N0O6gYDYNg9mlcJCv-jjb','18Lql5KmhlSBVUFh5CYVX4TWIzC0OYqrt','1gU37VdzL509T2CAZDvqrrAozd-TueL1m','19uH6nFigOfZPlim9sNh8MWj2n6bCmYn8','1JJ88r6-3YrbioTjVG-7F5ltFUM5ftwaz','1LXRW02yWc0jmBCBeLP1MOInZN5ru_TVZ','1tTIieqn_5vmkIxh7K67NfN_CWmy8FZCE','1pHnbwwth21q0FKbsWOzy32n-YfqhBbj3','1veu57VZlNHnqLkt9RFop0pmNBio6FUaS','1Q1xl6I4IqY_7PwuxfHGYbDUyCmjt1HXo','1vM-DuJFgfYgNT8FAxkXyZY_l1pw6MHDX','1YFI_EqbpEyFlSb2PY2KB4cer8oUvq7KG','1BoDVekNuyz5RUm1dE-aY1oaTMfFTnb5E','1fHn42I1I8ZHF-ipb43GMkVemZaka5nXB','14Ej33bqh0q_Aq6xYH7ahs8mTsJQhpBX9','1Gcznwx790FBA3kk6Iy0szVJIej8wfSFB','1Ilgx--Rr68hQjmIDAQCMJfE29cwmg2VB','1aLCe4O94hFzVt826vtOL-sE_HaE1sTzH','1nBzB-fGEiUqZTs_k_u7FxqTyZWwYHnk1','1h_b5Kd_vCvyqlFYihGWi8YIHUMRYpkbq','1uUeyDLDXRnUUUQCdiFf6PEFF_lrWk_jn','1SzCMDvjd-9n4bez6pr24N8CLZMwTvfBz','1qrxCkeWRRK36R0lFnLj4OKcgkBQJOVrb','1b6biMgF8qbE3yXRb3FCJdZxcnoubo4CV','1-1ZkcpQWgrGmAuqq6Kz7fGrkFnLMJcoz','1ZuzBkr-f6-Mvggw8B9nFwayRg5JxLVGl','11oAWP4WYIKnN0SasgAwnKLohF5vbxEeQ','1FOJyyztPvAT4D3jxXrm6ZPapi-AMAkaX','1lWKyAkxKc9aIBl_8am5EA6oEMnZC7833','15aEX4cDENH028jUdnnAZGaCQQ_v1wwx1'];
const $=s=>document.querySelector(s);
const opening=$('#opening'),site=$('#site'),openBtn=$('#openInvitation'),music=$('#bgMusic'),musicBtn=$('#musicButton');
let observer;
function setupObserver(){
 const els=document.querySelectorAll('.reveal:not(.is-visible)');
 if(!('IntersectionObserver'in window)){els.forEach(el=>el.classList.add('is-visible'));return;}
 if(!observer) observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.12,rootMargin:'0px 0px -5% 0px'});
 els.forEach(el=>observer.observe(el));
 setTimeout(()=>document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>{const r=el.getBoundingClientRect();if(r.top<innerHeight*1.15)el.classList.add('is-visible')}),700);
}
openBtn.addEventListener('click',async()=>{opening.classList.add('is-open');site.classList.remove('is-locked');setupObserver();try{await music.play();musicBtn.classList.add('is-playing')}catch(e){musicBtn.title='Chạm để bật nhạc'}});
musicBtn.addEventListener('click',async()=>{if(music.paused){try{await music.play();musicBtn.classList.add('is-playing')}catch(e){}}else{music.pause();musicBtn.classList.remove('is-playing')}});
const guest=new URLSearchParams(location.search).get('guest');if(guest){const v=guest.trim().slice(0,80);$('#guestGreeting').textContent=`Thân mời ${v} đến chung vui cùng Thắng & Yến`;$('#guestHidden').value=v}else $('#guestGreeting').textContent='Thân mời bạn đến chung vui cùng Thắng & Yến';
function tick(){const d=Math.max(0,new Date(CONFIG.weddingAt)-new Date());$('#days').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('#hours').textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');$('#minutes').textContent=String(Math.floor(d/60000)%60).padStart(2,'0');$('#seconds').textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}tick();setInterval(tick,1000);
const gallery=$('#gallery'),showMore=$('#showMore'),lightbox=$('#lightbox'),lightboxImage=$('#lightboxImage');let visibleCount=9;
const thumb=(id,s=1200)=>`https://drive.google.com/thumbnail?id=${id}&sz=w${s}`;
function openLightbox(src){lightboxImage.src=src;lightbox.classList.add('is-open');lightbox.setAttribute('aria-hidden','false')}
function renderGallery(){gallery.innerHTML='';galleryIds.slice(0,visibleCount).forEach((id,i)=>{const wrap=document.createElement('div');wrap.className=`gallery-item reveal ${i%3===0?'from-left':i%3===1?'from-bottom':'from-right'}`;const img=document.createElement('img');img.loading='lazy';img.alt=`Ảnh cưới Thắng và Yến ${i+1}`;img.src=thumb(id);img.addEventListener('click',()=>openLightbox(thumb(id,1800)));wrap.appendChild(img);gallery.appendChild(wrap)});showMore.style.display=visibleCount>=galleryIds.length?'none':'flex';setupObserver()}
showMore.addEventListener('click',()=>{visibleCount=Math.min(galleryIds.length,visibleCount+9);renderGallery()});renderGallery();setupObserver();
const heartField=$('#heartField');function spawnHeart(){if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const h=document.createElement('span');h.className='floating-heart';h.textContent=Math.random()>.4?'♡':'♥';h.style.left=`${Math.random()*96}%`;h.style.fontSize=`${16+Math.random()*22}px`;h.style.animationDuration=`${6+Math.random()*6}s`;h.style.setProperty('--drift',`${-70+Math.random()*140}px`);heartField.appendChild(h);setTimeout(()=>h.remove(),12500)}setInterval(spawnHeart,1250);for(let i=0;i<5;i++)setTimeout(spawnHeart,i*450);
const form=$('#rsvpForm'),status=$('#formStatus');form.addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(form).entries());payload.createdAt=new Date().toISOString();if(!CONFIG.rsvpEndpoint){localStorage.setItem('thangyen-rsvp-demo',JSON.stringify(payload));status.textContent='Đã lưu xác nhận trên thiết bị.';return}status.textContent='Đang gửi xác nhận...';try{await fetch(CONFIG.rsvpEndpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});status.textContent='Cảm ơn bạn! Thắng & Yến đã nhận được xác nhận ♥';form.reset()}catch(e){status.textContent='Chưa gửi được. Vui lòng thử lại sau.'}});
const giftModal=$('#giftModal');$('#openGift').addEventListener('click',()=>{giftModal.classList.add('is-open');giftModal.setAttribute('aria-hidden','false')});$('#closeGift').addEventListener('click',()=>giftModal.classList.remove('is-open'));giftModal.addEventListener('click',e=>{if(e.target===giftModal)giftModal.classList.remove('is-open')});$('#closeLightbox').addEventListener('click',()=>lightbox.classList.remove('is-open'));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.classList.remove('is-open')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){giftModal.classList.remove('is-open');lightbox.classList.remove('is-open')}});